#!/bin/bash
echo "Creating symbolic link for /usr/bin/lastfm-sync -> lastfm-rb-scrobbler/lastfm-sync"
ln -s $(realpath lastfm-rb-scrobbler/lastfm-sync) /usr/bin/lastfm-sync

echo "Creating symbolic link for /usr/bin/img-watch-and-move -> monitor-import-dir/img-watch-and-move"
ln -s $(realpath monitor-import-dir/img-watch-and-move) /usr/bin/img-watch-and-move
#ln -s $(realpath monitor-import-dir/monitor-photo-uploads.service) /etc/systemd/system/monitor-photo-uploads.service

echo "Creating symbolic link for /usr/bin/organize-and-move -> organize-and-move"
ln -s $(realpath organize-and-move) /usr/bin/organize-and-move
