#!/usr/bin/bash

progress-bar() {
	local curr=$1
	local len=$2
	
	local length=$((COLUMNS/2))
	local percent_done=$((curr * 100 / len))
	local num_bars=$((percent_done * length / 100))

	local bar_char="#"
	local empty_char="-"
	local i=0
	local s='['		
	for ((i = 0; i < num_bars; i++)); do
		s+=$bar_char
	done
	for ((i = num_bars; i < length; i++)); do
		s+=$empty_char
	done
	s+=']'

	echo -ne "$s $curr/$len ($percent_done%)\r"
}

process-file() {
	local file=$1
	# 'magick "$0" -resize 300x300\> "${0%.*}"-new.jpg; rm "$0"; mv "${0%.*}"-new.jpg "${0%.*}".jpg' {} \;
	sleep .1
}


shopt -s globstar nullglob

echo 'finding files now'
files=(./**/*.jpg)
len=${#files[@]}
echo "found $len cover art files"

i=0
for file in "${files[@]}"; do
	progress-bar "$((i+1))" "$len"
	process-file "$file"
	((i++))
done

echo
