#!/bin/bash
# upload a scrobbler log file from music player to last FM service

# -f [path to .scrobbler.log]
# -o [time offset in hours]
if [ -z $1 ] && [ -a .scrobbler.log  ]; then
    echo "using .scrobbler.log in curr dir"
    LOG_FILE=".scrobbler.log"
elif [ -z $1 ]; then
    echo "run with path to scrobbler log"
    echo "$0 /path/to/.scrobbler.log"
    exit
elif [ -a "$1"  ]; then
    LOG_FILE="$1"
fi

EXE="build/rb-scrobbler"
TIME_OFFSET=$(date +%z | sed -e 's/0//g')

# run the scrobbler in docker container
docker run --rm -it -v "$LOG_FILE":/data/input -v rb-scrobbler-config:/root/.config rb-scrobbler:alpine -f /data/input -o "$TIME_OFFSET"
# -n "delete-on-success"
